name: Unit & Component Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
      - ready_for_review

jobs:
  tests:
    name: Run unit tests and CT tests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    env:
      VITE_APP_GIT_TAG: ${{github.ref}}
      VITE_APP_GIT_SHA: ${{github.sha}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.3.0
        uses: actions/setup-node@v1
        with:
          node-version: '17.3.0'
      - name: Test all (client and server)
        run: npm test
